---
- name: add homebrew taps
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ taps }}"

- name: install homebrew formulae
  homebrew:
    name: "{{ item }}"
  loop: "{{ formulae }}"

- name: install homebrew casks 
  homebrew_cask:
    name: "{{ item }}"
  loop: "{{ casks }}"

- name: set up dock
  ignore_errors: true
  script:
    cmd: scripts/dock.sh
